# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5189f1fc60815aa6dae04e5c0bbaf702234994c1f4297b1274e0d88c61cb40d52b05a4e8bd4795f1583a4da61e18f373573b937c5f7adc7613df586abf64f610

test:
  secret_key_base: 27e09f032761a27c1b51f058c996786f1ea2847c034fd21af70ec6e6eb24342d20d76017473fea43a38c44a4856cf27515d32e818cfc4f934f1d2f0ee5504d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
